name: new_design_demo

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.1
  intl: ^0.20.2
  flutter_html: ^3.0.0
  flutter_background_geolocation: ^5.0.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  battery_plus: ^7.0.0
  flutter_local_notifications: ^20.1.0
  fluttertoast: ^9.0.0
  device_info_plus: ^12.3.0
  geocoding: ^4.0.0
  path_provider: ^2.1.5
  geofence_service: ^6.0.0+1
  percent_indicator: ^4.2.5
  google_maps_flutter: ^2.15.0
  flutter_screenutil: ^5.9.3
  file_picker: ^10.3.10
  open_file: ^3.5.11
  flutter_bloc: ^9.1.1
  get: ^4.7.3
  image_picker: ^1.2.2
  table_calendar: ^3.2.0
  sqflite: ^2.4.2+1
  path: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/resources/icons/playstore.png"


flutter:
  uses-material-design: true

  assets:
    - lib/resources/icons/
    - lib/resources/images/